# Generated by Django 4.2 on 2025-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
