# Generated by Django 4.2 on 2025-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('late', 'Late'), ('finished', 'Finished')], default='in_progress', max_length=15),
        ),
    ]
