# Generated by Django 4.2 on 2025-06-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_finished_at_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, max_length=15),
        ),
    ]
